name: Build and deploy to K8s

# on:
#   push:
#     branches:
#       - dev
#       - staging
#       - master

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
  setting-environment:
    name: setting-environment
    runs-on: ubuntu-latest
    outputs:
      environment-name: ${{ steps.get-environment.outputs.environment-name }}
    steps:
      - name: Determine Environment
        id: get-environment
        shell: python
        run: |
          import os
          env = 'none'
          if os.environ['GITHUB_REF'] == 'refs/heads/dev':
            env = 'dev'
          elif os.environ['GITHUB_REF'].startswith('refs/heads/feature/'):
            env = 'dev'
          elif os.environ['GITHUB_REF'] == 'refs/heads/staging':
            env = 'staging'
          elif os.environ['GITHUB_REF'] == 'refs/heads/master':
            env = 'prod'
          print('::set-output name=environment-name::' + env)

  Deploy:
    runs-on: ubuntu-latest
    needs: setting-environment
    name: Deploy to ${{ needs.setting-environment.outputs.environment-name }}
    environment: ${{ needs.setting-environment.outputs.environment-name }}
    if: ${{ needs.setting-environment.outputs.environment-name != 'none' }}
    steps:
      - name: Deploying to Dev environment
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: |
            apply -f ./deployment
            get pods
            get svc
